@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Profiler *-right-> "1" UniquePersonList
Profiler *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Id
Person *--> Phone
Person *--> Email
Person *--> Project
Person *--> Progress
Person *--> "0..1" Log
@enduml
